### ISSUE TITLE
Add Raven's talk at LACMA to news

### ISSUE THREAD

**Issue by amandamcg** [foodoasisla/site#123]
![raven](https://user-images.githubusercontent.com/8716226/28347788-11fe9d46-6bee-11e7-93d7-17850dc20c80.jpg)
![image uploaded from ios 4](https://user-images.githubusercontent.com/8716226/28347790-120cf7a6-6bee-11e7-84eb-332d2d406b9d.jpg)
![image uploaded from ios 3](https://user-images.githubusercontent.com/8716226/28347792-1238338a-6bee-11e7-8d57-48bdb0931416.jpg)
![image uploaded from ios 2](https://user-images.githubusercontent.com/8716226/28347789-120aaf8c-6bee-11e7-93b2-8a8aaaf80ff5.jpg)

Hey people @here! Our very own Raven Hardison is going to give a short presentation about Food Oasis LA at LACMA this Thursday, July 13. Come see her and enjoy the _pecha kuchas!_

https://www.eventbrite.com/e/grants-reactionresponsereality-the-arts-in-los-angeles-in-2017-registration-35543543696

**Comment by jimthoburn** [comment]
This news article is live!

https://foodoasis.la/news/2017/07/13/lacma/
