### ISSUE TITLE
Translate the site navigation into Spanish

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#15]
The content for the navigation is in this file…
https://github.com/foodoasisla/site/blob/master/_data/locales.yml

And you can see an example Spanish page here…
https://foodoasis.la/es/

[Halina](https://github.com/hvz90) can help with the translation.

![navigation](https://cloud.githubusercontent.com/assets/926616/21310843/fecb8d98-c598-11e6-949b-dd1e0e8aaaf9.png)

**Comment by jimthoburn** [comment]
https://github.com/foodoasisla/site/pull/64

Nice work on this one, @MarioEsparza !

**Comment by ExperimentsInHonesty** [comment]
Once the site is redeveloped we will re-translate it.
