### ISSUE TITLE
Link to the Spanish translation in the site map

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#23]
Here’s some information from Google’s webmaster guidelines…
https://support.google.com/webmasters/answer/2620865?hl=en

The site map file is located here…
https://github.com/foodoasisla/site/blob/master/sitemap.xml

And the Spanish pages are located here…
https://foodoasis.la/es/
https://foodoasis.la/es/about/

**Comment by robertisandor** [comment]
I've made an attempt to solve this issue. Here's the link for the related pull request.
https://github.com/foodoasisla/site/pull/65
Feel free to let me know if there's anything else to improve upon.

**Comment by jimthoburn** [comment]
Awesome, Robert. Those changes are live!

https://foodoasis.la/sitemap.xml
