### ISSUE TITLE
Create a redirect to the survey form hosted by Typeform

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#42]
Let’s create a redirect from [https://foodoasis.la/survey](https://foodoasis.la/survey) to [https://foodoasisla.typeform.com/to/ojwSQ9](https://foodoasisla.typeform.com/to/ojwSQ9) to make it easier to reach the survey.

## Example file

Here’s an example redirect file:
[https://github.com/foodoasisla/site/blob/master/prototype.md](https://github.com/foodoasisla/site/blob/master/prototype.md)

You can try it out by visiting this URL:
[https://foodoasis.la/prototype/](https://foodoasis.la/prototype/)

## Steps

Here are some steps you can follow to make a new redirect…

1. Create a new file with a name that matches the URL you want to redirect from. For example, a file named `food.md` could act as a redirect for `foodoasis.la/food`. You can place this file at the root of the website.

2. Copy and paste this example code into your new file:
```
---
layout: default

title: Redirecting to Example Location

redirect: https://example.com
---

# Redirecting to Example Location…

[https://example.com](https://example.com)
```

3. Change the “redirect” URL to the place where you want to redirect to.

4. Update the page title and content with information about the redirect.

## Background

Since the website is hosted on GitHub, redirects are done on the client side. When the site is generated, the “redirect” URL is translated into a refresh element…
```
<meta http-equiv="refresh" content="0; url=https://example.com" />
```

The title and content of the page are helpful to search engines and also provide a fallback for users–just in case the meta element doesn’t work.

**Comment by georgefpope** [comment]
Done, needs to be tested.

**Comment by jimthoburn** [comment]
Thanks, George. Looks good to me!  : )

https://foodoasis.la/survey
