### ISSUE TITLE
Add photos for the Erika J. Glazer Community Garden

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#76]
Malak took some beautiful photos of the [Erika J. Glazer Community Garden](https://foodoasis.la/community-garden/erika-j-glazer/) that we could add to the website.

Step 1: Ask @malakdlo if it’s okay to add his photos to the website.

Step 2: [Download the photos](https://drive.google.com/drive/folders/0B_64JxVgLHIZNlhselZFd21PZ00?usp=sharing)

Step 3: Upload the photos to GitHub. [/assets/images/photos](https://github.com/foodoasisla/site/tree/master/assets/images/photos) might be a good place for them.

Step 4: Add them to [the markdown file](https://github.com/foodoasisla/site/edit/master/_community-garden/erika-j-glazer.md)

Here’s an example of a location with images…
https://github.com/foodoasisla/site/blob/master/_farmers-market/santa-monica-downtown.md

And here’s some information about using markdown…
https://guides.github.com/features/mastering-markdown/

**Comment by SomeRandom42** [comment]
commit done ! Thanks for the photos malakdlo1 Updated on https://github.com/foodoasisla/site/blob/master/_community-garden/erika-j-glazer.md

**Comment by jimthoburn** [comment]
Thanks, Patrick! Those photos are live on the website:
https://foodoasis.la/community-garden/erika-j-glazer/
