### ISSUE TITLE
Fix address for Long Beach Farmers Market

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#79]
The address on this location includes a tip for finding the market…
https://foodoasis.la/farmers-market/long-beach-downtown-cfm/

Let‘s move that information to the description area, after the data. Here‘s an example…
https://github.com/foodoasisla/site/blob/master/_locations/everytable-downtown-la.md

You can edit the _Long Beach Farmers Market_ page here…
https://github.com/foodoasisla/site/blob/master/_farmers-market/long-beach-downtown-cfm.md

**Comment by tamurafatherree** [comment]
Here you go 
https://github.com/foodoasisla/site/commit/1b5b7183f4727a137c83c1bb9ceb006bafc8ae19

**Comment by jimthoburn** [comment]
Nice, Tamura! 💯

That update is live…
https://foodoasis.la/farmers-market/long-beach-downtown-cfm/
