### ISSUE TITLE
Fix hours for Ralphs locations

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#80]
The hours for these two Ralphs locations don’t seem quite right.

1. https://foodoasis.la/supermarket/ralphs-645-w-9th-st/
2. https://foodoasis.la/supermarket/ralphs-11727-w-olympic-blvd/

Let’s look them up on the web, and fix the hours. You can make changes by editing these markdown files…

1. https://github.com/foodoasisla/site/edit/master/_supermarket/ralphs-645-w-9th-st.md
2. https://github.com/foodoasisla/site/edit/master/_supermarket/ralphs-11727-w-olympic-blvd.md

After a few minutes, your changes will appear on the staging website…
1. https://staging.foodoasis.la/supermarket/ralphs-645-w-9th-st/
2. https://staging.foodoasis.la/supermarket/ralphs-11727-w-olympic-blvd/

Bonus points: Look for other locations with broken hours. One way to do this would be to download the project with [GitHub Desktop](https://desktop.github.com) and then search through the markdown files using a text editor like [Atom](https://atom.io).

**Comment by SomeRandom42** [comment]
fixed these here are my links to pull request
https://github.com/foodoasisla/site/pull/151
https://github.com/foodoasisla/site/pull/152

**Comment by jimthoburn** [comment]
Awesome, Patrick. Those updates are live…

https://foodoasis.la/supermarket/ralphs-645-w-9th-st/
https://foodoasis.la/supermarket/ralphs-11727-w-olympic-blvd/
