### ISSUE TITLE
Update the list of contributors

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#85]
Let’s update the [contributors on the team page](https://foodoasis.la/team/#contributors-thanks-everyone) with the latest names from our Google Spreadsheet (@ravencofer or @joshuazrobins can provide access).

Here’s a page where you can make the changes…
https://github.com/foodoasisla/site/edit/master/team.md

Don’t forget to add yourself!   : )

**Comment by joshuazrobins** [comment]
Duplicated by #118
