### ISSUE TITLE
Add Grand Central Market to the map

### ISSUE THREAD

**Issue by jimthoburn** [foodoasisla/site#87]
There are two vendors who sell produce, inside of Grand Central Market…

District Market
http://www.grandcentralmarket.com/vendors/542/district-market

Torres Produce
http://www.grandcentralmarket.com/vendors/37/torres-produce

Here’s a form you can use to add locations…
https://foodoasis.la/add/

And here are some photos…

![grand-central-market](https://user-images.githubusercontent.com/926616/27504996-f60065f0-5849-11e7-8400-f6211d398221.jpg)

![district-market](https://user-images.githubusercontent.com/926616/27504997-f8fe0d5c-5849-11e7-95c0-77d64e857943.jpg)

![torres-produce](https://user-images.githubusercontent.com/926616/27504998-fa92c324-5849-11e7-81c6-b845b2a41c70.jpg)

**Comment by joshuazrobins** [comment]
Completed, 2 pull requests are awaiting review.

**Comment by jimthoburn** [comment]
Those two new locations are live on the website!

District Market
https://foodoasis.la/locations/district-market/

Torres Produce
https://foodoasis.la/locations/torres-produce/
