### ISSUE TITLE
Make "use my location" button more prominent in filters

### ISSUE THREAD

**Issue by amandamcg** [foodoasisla/site#92]
<img width="1056" alt="screen shot 2017-06-27 at 8 18 43 pm" src="https://user-images.githubusercontent.com/8716226/27619306-3824e616-5b76-11e7-9c52-a8065413762a.png">
<img width="1056" alt="screen shot 2017-06-27 at 8 18 43 pm" src="https://user-images.githubusercontent.com/8716226/27619316-4ef39bd0-5b76-11e7-8639-5a54c88a29cc.png">

Here is the svg icon
[gps.svg.zip](https://github.com/foodoasisla/site/files/1107475/gps.svg.zip)

**Comment by jimthoburn** [comment]
This change is live!

https://foodoasis.la/search/
