### ISSUE TITLE
Update design of the filter button

### ISSUE THREAD

**Issue by amandamcg** [foodoasisla/site#93]
On desktop, can we change the design of the filter button

<img width="166" alt="screen shot 2017-06-27 at 8 27 20 pm" src="https://user-images.githubusercontent.com/8716226/27619426-0a86022a-5b77-11e7-9531-76c9728aeef1.png">

[filter.svg.zip](https://github.com/foodoasisla/site/files/1107479/filter.svg.zip)

**Comment by SomeRandom42** [comment]
How do you want this changed? rounded edges? change the color, use a funnel instead?

**Comment by jimthoburn** [comment]
This new icon is in production now.
https://foodoasis.la/locations/

Thanks @amybaldwindev !

https://github.com/foodoasisla/site/pull/162/commits/fed07ea4727432c0e6c57ab0235a0cee5870b858
