### ISSUE TITLE
Add headers to the filters list

### ISSUE THREAD

**Issue by amandamcg** [foodoasisla/site#94]
This is a quick mock up, so the alignment is wrong, but you get the idea.

![filters - headers](https://user-images.githubusercontent.com/8716226/27619606-835e131c-5b78-11e7-9979-56e23f8f7384.png)

**Comment by kimhjona** [comment]
*added the headers just now

**Comment by jimthoburn** [comment]
Awesome, Jon! That change is live…

https://foodoasis.la/filters/
